# Generated by Django 5.1.3 on 2024-12-21 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('cuisine', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, 'Rating cannot be negative')])),
                ('image', models.ImageField(blank=True, upload_to='restaurant_images/')),
            ],
        ),
    ]
