# Generated by Django 5.1.3 on 2024-12-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
