# Generated by Django 5.1.3 on 2025-01-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
