# Generated by Django 5.1.3 on 2025-01-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurant_google_maps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('French', 'French'), ('Khmer', 'Khmer'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('American', 'American'), ('Mexican', 'Mexican'), ('Other', 'Other')], max_length=100),
        ),
    ]
